version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list

      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic code-question-update-request-to-core-service --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic code-question-update-response-from-core-service --delete --if-exists
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-question-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-question-response --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-question-request-code-assessment --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-question-response-code-assessment --delete --if-exists
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-user-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic course-user-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic code-assessment-user-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic user-response --delete --if-exists
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic core-organization-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic course-organization-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic organization-response --delete --if-exists
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic calendar-event-update-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic calendar-event-update-response --delete --if-exists
      
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic code-question-update-request-to-core-service --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic code-question-update-response-from-core-service --replication-factor 3 --partitions 3
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic core-question-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic core-question-response --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic  core-question-request-code-assessment --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic  core-question-response-code-assessment --replication-factor 3 --partitions 3

      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic core-user-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic course-user-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic code-assessment-user-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic user-response --replication-factor 3 --partitions 3
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic core-organization-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic course-organization-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic organization-response --replication-factor 3 --partitions 3
      
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic calendar-event-update-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic calendar-event-update-response --replication-factor 3 --partitions 3
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}