version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    ports:
      - "8890:8080"
    command: start-dev
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  postgres_keycloak:
    image: postgres:15
    command: postgres -c 'max_connections=200'
    volumes:
      - "./volumes/postgres_keycloak:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5436:5432"
    networks:
      - ${GLOBAL_NETWORK:-kafka}