server:
  port: 9098

logging:
  level.root: DEBUG
  level:
    com.backend.programming.learning.system.gateway.service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

gateway-service:
  timeout-ms: 10000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:9999}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 15s
      connect-timeout: 15s

security:
  paths-to-ignore: /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  auth:
    converter:
      resource-id: spring-client-api-rest
      principle-attribute: preferred_username

keycloak:
  realm: spring-boot-realm-dev
  domain: localhost:8890
  admin-client-id: admin-cli
  admin-client-secret: bTEi5t1OKE7l97ij9wYjAMqqYA4NCod8
  client: spring-client-api-rest
  client-secret: pE2Lz9RL01YGE15800wDxRfnz2KFuCgX
  urls: http://${keycloak.domain}

springdoc:
  api-docs:
    urls:
      - name: core
        url: /v3/api-docs/core
      - name: auth
        url: /v3/api-docs/auth
      - name: course
        url: /v3/api-docs/course
      - name: code-assessment
        url: /v3/api-docs/code-assessment
  swagger-ui:
    urls:
      - name: core
        url: /swagger-ui/core
      - name: auth
        url: /swagger-ui/auth
      - name: course
        url: /swagger-ui/course
      - name: code-assessment
        url: /swagger-ui/code-assessment

---
spring.config.activate.on-profile: prod
# Disable springdoc-openapi
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  paths-to-ignore: /actuator/**