logging:
  level.root: DEBUG
  level:
    com.backend.programming.learning.system.gateway.service: DEBUG

server:
  port: 9098

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:9999}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!
  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 1s