logging:
  level.root: DEBUG

server:
  port: 9098

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  profiles:
    active: gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:9999}"
  cloud:
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!