logging:
  level.root: DEBUG

server:
  port: 9098

spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:9999}"
  cloud:
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!
  application:
    name: gateway-service
  profiles:
    active: gateway