server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    appname: service-registry-cluster
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    ROOT: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

log:
  app-name: discovery-service
