server:
  port: 8183

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    com.backend.programming.learning.system: DEBUG

code-assessment-service:
  code-question-update-response-from-core-service-topic-name: code-question-update-response-from-core-service
  code-question-update-request-to-core-service-topic-name: code-question-update-request-to-core-service

  question-request-code-assessment-topic-name: core-question-request-code-assessment
  question-response-code-assessment-topic-name: core-question-response-code-assessment

  code-assessment-user-request-topic-name: code-assessment-user-request
  user-response-topic-name: user-response

  outbox-scheduler-fixed-rate: 2000
  outbox-scheduler-initial-delay: 2000

  question-request-topic-name: core-question-request

  assessment-external-service-ip: localhost
  assessment-external-service-port: 2358

  accepted-status-description: Accepted

spring:
  application:
    name: code-assessment-service
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:9999}
  cloud:
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!
  datasource:
    url: jdbc:postgresql://localhost:5432/code-assessment-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: localdb
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always
      data-locations: classpath:init-data.sql
      schema-locations: classpath:init-schema.sql

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: none
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  create-code-question-consumer-group-id: create-code-question-topic-consumer
  question-request-consumer-group-id: question-request-topic-consumer
  code-assessment-service-user-request-group-id: code-assessment-service-user-request-topic
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3  #increase the partition to increase this
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

springdoc:
  api-docs:
    path: /code-assessment/v3/api-docs
  swagger-ui:
    path: /code-assessment/swagger-ui

security:
  paths-to-ignore: /code-assessment/v3/api-docs, /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

log:
  appName: code-assessment-service
---
spring.config.activate.on-profile: prod
# Disable springdoc-openapi
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  paths-to-ignore: /actuator/**