server:
  port: 8183
logging:
  level:
    com.backend.programming.learning.system: DEBUG

code-assessment-service:
  code-question-create-request-to-core-service-topic-name: code-question-create-request-to-core-service
  code-question-create-response-from-core-service-topic-name: code-question-create-response-from-core-service

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/code-assessment-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always

