server:
  port: 9999

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/6BrosT/config-server-repository.git
          skip-ssl-validation: true
          default-label: main
#          force-pull: true
          clone-on-start: true
          timeout: 10
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}